[package]
name = "impbind"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.36", features = ["derive"] }
comfy-table = "7.1.4"
thiserror = "2.0.12"
log = "0.4"
pretty_env_logger = "0.4"
