[package]
name = "impbind"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.36", features = ["derive"] }
thiserror = "2.0.12"
tracing = "0.1"
tracing-subscriber = { version = "0.3" }
